Global Registry function for node metadata management
wmo-im/wis2-guide pull request #26
Opened 2023-09-01 11:49 UTC by kurt-hectic

* Introduction of a Global Registry (GR) function to manage metadata needed by GB to discover registered WIS nodes and for WIS nodes to obtain source IP addresses of GB and GC 
* Procedures for WIS2 nodes to let GB and GC connect 
* Procedures for WIS2, GC and GB to manage relevant metadata in the GR

2023-09-01 12:31 UTC, golfvert requested changes

2023-09-01 12:31 UTC, golfvert commented on guide/sections/global-services.adoc
> +* The roles of the Global Registry is to make available the information required for Global Infrastructure and WIS2 nodes to connect with each other.
I don't think we need to introduce the term" Global Infrastructure". I'd prefer to keep Global Services. 
We also have to be consistent. Here WIS2 Node is used. In other PR it is WIS Node. So far we used WIS2 Nodes. That would be my preference.

2023-09-01 12:31 UTC, golfvert commented on guide/sections/global-services.adoc
> +* The Global Registry makes available to Global Caches the list of registered WIS2 Nodes. The following metadata is made available for each WIS2 Node: hostname and port(s) of local broker, center_id,
The Global Caches are not on the "front" of the connectivity. GBs are.
So, we could have "The Global Registry makes available to Global Services the list of registered WIS2 Nodes"

2023-09-01 12:31 UTC, golfvert commented on guide/sections/global-services.adoc
> +* The Global Registry provides authorized contacts the means to update information about their WIS2 Node or Global Infrastrucure.
Same here. Infrastructure. Use Services.

2023-09-01 12:38 UTC, golfvert requested changes

2023-09-01 12:38 UTC, golfvert commented on guide/sections/wis2node.adoc
> +This section describes the process used to register or remove a WIS2 node within WIS2. To register one or more WIS nodes, the Member responside for the node needs to be designated as a NC or DCPC.
WIS or WIS2. I'd prefer WIS2.
Add at the end by the PR of the country.

2023-09-01 12:38 UTC, golfvert commented on guide/sections/wis2node.adoc
> +A WIS2 node shall allow at least one Global Broker and Global Cache to connect to its local broker and web storage. For this, the WIS2 node shall allow the outgoing IP addresses used by the Global Br
At least two of each... Redundancy.
No, Global Cache don't subscribe to WIS2 Node. Only to GB. 
No one but GBs are subscribing to WIS2 Nodes, GC and GBs.

Replace by:

A WIS2 node shall allow at least two Global Broker to connect to its local broker and at least two Global Cache to its web storage. For this, the WIS2 node shall allow the outgoing IP addresses used by the Global Broker and Global Cache to establish connections to broker and web-storage, and allow the Global Broker to subscribe to the topic corresponding to this WIS2 node. Username and password used to protect the MQTT subscription will be part of the Global Registry.

2023-09-01 12:38 UTC, golfvert commented on guide/sections/wis2node.adoc
> +The list of IP addresses used by Global Brokers and Caches can be obtained from the Global Registry. If a WIS2 node implements source IP filtering to grant a Global Broker and Global Cache access, it
The list of IP addresses used by Global Brokers and Caches can be obtained from the Global Registry. If a WIS2 node implements source IP filtering to grant Global Brokers and Global Caches access, it shall implement changes to its filtering within one month of the changes being published to the Global Registry.

2023-10-19 13:41 UTC, kurt-hectic commented
@golfvert  and @tomkralidis  . Can this be merged? I believe all Remy's comments are addressed. When merging the Secretariat will make sure consistent terminology is used for nodes and services.

2023-10-19 23:03 UTC, tomkralidis commented
@kurt-hectic 

- should #27 be closed?
- we have recently updated the structure of the guide, which will required updates to fix the resulting merge conflicts in this PR

2024-01-08 19:32 UTC, tomkralidis commented
@kurt-hectic @golfvert closing this PR and invite a new PR based on the new structure (and to resolve merge conflicts).

2024-01-08 19:32 UTC, closed without merging