Metrics
wmo-im/wis2-guide pull request #31
Opened 2023-09-11 11:28 UTC by kaiwirt

Draft section on metrics, including the tables from github

2023-10-03 11:17 UTC, tomkralidis approved these changes

2023-10-03 11:17 UTC, tomkralidis commented on guide/sections/wis-metrics.adoc
> +The roles of centers with respect to the monitoring as well as the content and structure of metrics specific to WIS2 (e.g., data availability) are described below.
centers -> centres ("centre" is being used across the document).

2023-10-03 11:17 UTC, tomkralidis commented on guide/sections/wis-metrics.adoc
> +The Global Monitoring (Centers) are the entry points for users and provide the monitoring results. The main task of the Global Monitoring is to regularly query the provided metrics from the relevant
Centers -> Centres

2023-10-03 11:17 UTC, tomkralidis commented on guide/sections/wis-metrics.adoc
> +WMO Programs can define monitoring requirements in order to be able to verify if the program's requirements are met. To do so, they need to define the relevant metrics. Metrics not directly related t
Centers -> Centres

2023-10-03 11:17 UTC, tomkralidis commented on guide/sections/wis-metrics.adoc
> +WMO Programs can define monitoring requirements in order to be able to verify if the program's requirements are met. To do so, they need to define the relevant metrics. Metrics not directly related t
Should there be a link to openmetrics.io (or in an Annex)?

2023-10-03 11:17 UTC, tomkralidis commented on guide/sections/wis-metrics.adoc
> +==== Sensor Centers and WMO programs
Centers -> Centres

2023-10-03 11:18 UTC, tomkralidis requested changes
Minor changes requested.

2023-10-04 07:55 UTC, kaiwirt commented
Renamed to centre and added a reference to openmetrics.io

2023-10-04 10:38 UTC, tomkralidis approved these changes

2023-10-04 10:38 UTC, merged